""
"Single String"
"Double" "Strings"
"double quote->""<-double quote"
"Your string should ignore these reserved words -> program var array not"
" Test whether you can ignore comments // This is a comment "
" Test whether you can ignore comments /* This is a comment */ "
" Test whether you can ignore comments // This is a comment /* This is a comment */ "
" Single-Line With comment // This is a comment "
" Single-Line With comment  /* This is a comment  */ "
