name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - run: ls
    - name: install flex
      run: sudo apt install flex
      
    - name: install flex-dev
      run: sudo apt install libfl-dev

    - name: Install dependencies
      run: make prepare
      
    - name: Run check
      run: make test
      
    
